### PR TITLE
Improved installation guide, added packaging status

### PR DESCRIPTION
**Pull request by ghost**
Discussed in #7

### CODE REVIEW

**Comment by SimonTeixidor** [comment]
Hi! Thanks for this contribution. I would prefer to drop the `From PolarRepo (prebuilt package)` section. I'm sure your repo is safe to use, but I still don't want to be seen as endorsing a repository that I'm not hosting or monitoring myself. I notice that this information is available on the AUR page anyway, so anyone who prefers a prebuilt package should be able to find it.

**Comment by ghost** [comment]
Sure, I understand... I will remove it now :)

**Comment by ghost** [comment]
@SimonPersson I stripped it.

**Comment by ghost** [comment]
I still need the latest version tagged in #7

**Comment by SimonTeixidor** [comment]
Thank you! I've merged the PR. I also pushed a small bugfix and a version bump, with a tag this time :)

**Comment by ghost** [comment]
Thanks, I will update the AUR package now :)

**Comment by ghost** [comment]
@SimonPersson Just letting you know, I have bumped the version in the AUR and made a small improvement to the package. I have also pushed the updated package to my unofficial repository.

I am watching this repository, so I will be notified on any updates :)

Thanks for merging the pull request!

**Pull request merged**
